### ISSUE TITLE
 Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Devhelp#1]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fi1-linux.softpedia-static.com%2Fscreenshots%2FDevhelp_1.png&f=1

https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fhelp.gnome.org%2Fmisc%2Frelease-notes%2F3.8%2Ffigures%2Fdevhelp.png&f=1

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by ghost** [comment]
This should be done upstream, not here.
