### ISSUE TITLE
Update to Gnome SDK 40

### ISSUE THREAD

**Issue by akurtakov** [flathub/org.gnome.Devhelp#10]
On update flatpak prints:
Info: org.gnome.Sdk//3.38 is end-of-life, with reason:
   The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.gnome.Devhelp

**Comment by ebassi** [comment]
I've just published the 40.1 release, which depends on org.gnome.Platform//40.
