### ISSUE TITLE
Devhelp doesn't detect books on local data dir

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/org.gnome.Devhelp#3]
I have installed the books of pygobject in `$HOME/.local/share/devhelp/` but they are not detected by the Flatpak version.
Is there anything that should be done in order to fix this? Installing the package from fedora's repository works as expected

**Comment by TingPing** [comment]
It should be easy to get `$HOME/.local/share/devhelp` working, just a minor patch to always add that to the paths it reads even when `$XDG_DATA_HOME` is set somewhere else.

The host `/usr/share` requires more work though.

**Comment by ghost** [comment]
RTFM: https://gitlab.gnome.org/GNOME/devhelp/blob/master/README

**Comment by philn** [comment]
In case some lost soul like me drives by, the interesting doc was moved to https://gitlab.gnome.org/GNOME/devhelp/-/blob/master/help/C/installing-api-documentation.page ...
