### ISSUE TITLE
Devhelp uses EOLed runtime

### ISSUE THREAD

**Issue by akurtakov** [flathub/org.gnome.Devhelp#7]
Flatpak started to give me:
Info: org.gnome.Sdk is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.
Info: org.gnome.Sdk.Locale is end-of-life, with reason: The GNOME 3.32 runtime has reached end of life. Please upgrade to a newer version.

Trying to uninstall this org.gnome.Sdk runtime ends up with:
Error: Can't remove org.gnome.Sdk/x86_64/3.32, it is needed for: org.gnome.Devhelp/x86_64/stable
error: Failed to uninstall org.gnome.Sdk: Can't remove org.gnome.Sdk/x86_64/3.32, it is needed for: org.gnome.Devhelp/x86_64/stable

Please update to use org.gnome.Sdk 3.36

**Comment by ghost** [comment]
Devhelp is now updated, thanks for your contribution!
