### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/org.gnome.Devhelp#9]
The latest update wasn't published https://flathub.org/builds/#/builders/12/builds/1281
as the appdata file seems to be invalid.

**Comment by ghost** [comment]
Thanks for the bug report. It needs to be fixed upstream, then I will do a new Devhelp release, and finally it can be updated here.

**Comment by ghost** [comment]
Do you know what's wrong in the AppData file?

https://gitlab.gnome.org/GNOME/devhelp/-/blob/master/data/org.gnome.Devhelp.appdata.xml.in

Maybe it needs release information?

**Comment by bilelmoussaoui** [comment]
Yes; that what it lacks; the release tags are required on Flathub, see https://github.com/flathub/flathub/wiki/App-Requirements#Appstream

**Comment by ghost** [comment]
Cool, thanks, I'll look at it.

**Comment by ghost** [comment]
Fixed upstream, I'll do a new release soon, or I'll just wait for GNOME 3.36.1 for doing the release.

**Comment by ghost** [comment]
Done. Devhelp 3.36.1 released.

**Comment by bilelmoussaoui** [comment]
Thanks
